# Generated by Django 4.2.4 on 2023-09-06 04:21

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_carimage_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carimage',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=100, scale=None, size=[1920, 1080], upload_to='cars_images/', verbose_name='Основная фотография'),
        ),
    ]
