# Generated by Django 4.2.4 on 2023-09-05 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='description',
            field=models.TextField(max_length=400, verbose_name='Описание'),
        ),
    ]
