# Generated by Django 4.2.4 on 2023-09-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0004_review_contact_created_setting_facebook_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='cars',
            field=models.ImageField(blank=True, null=True, upload_to='slider/', verbose_name='Фотография машины'),
        ),
        migrations.AddField(
            model_name='setting',
            name='logistics',
            field=models.ImageField(blank=True, null=True, upload_to='slider/', verbose_name='Фотография логистики'),
        ),
        migrations.AddField(
            model_name='setting',
            name='spare_parts',
            field=models.ImageField(blank=True, null=True, upload_to='slider/', verbose_name='Фотография запчастей'),
        ),
        migrations.AddField(
            model_name='setting',
            name='special_equipment',
            field=models.ImageField(blank=True, null=True, upload_to='slider/', verbose_name='Фотография спецтехники'),
        ),
    ]
